### ISSUE TITLE
Could  you add 'tag' to the fields options?

### ISSUE THREAD

**Issue by TonyXiang** [domharrington/node-gitlog#69]
for git tag infomations

**Comment by hipstersmoothie** [comment]
If you make the PR I'll happily merge and release it!

**Comment by jigarzon** [comment]
@hipstersmoothie i added a pull request on this issue, very simple

**Comment by thegoatherder** [comment]
@hipstersmoothie  @jigarzon 
Including `tag` in `fields` results in:

```ascii
(node:306360) UnhandledPromiseRejectionWarning: Error: Unknown field: tag
    at F:\Code\node_modules\gitlog\dist\gitlog.cjs.development.js:166:15
    at Array.forEach (<anonymous>)
    at createCommandArguments (F:\DNV\Code\node_modules\gitlog\dist\gitlog.cjs.development.js:164:20)
    at gitlog (F:\DNV\Code\node_modules\gitlog\dist\gitlog.cjs.development.js:215:26)   
    at process (F:\DNV\Code\log-gen.js:49:25)
    at Object.<anonymous> (F:\DNV\Code\log-gen.js:71:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```
