### ISSUE TITLE
PR#76 is merged to master but not released?

### ISSUE THREAD

**Issue by thegoatherder** [domharrington/node-gitlog#85]
@domharrington thanks for this great repo.

I see PR #76 was merged to `master` on 21 Mar 2022... however the last release is v4.0.4 made on 5 Jan 2021.
Can we have a v4.1 release to include these changes please?  Without it the README documentation is wrong. The new `tag` option is included on the docs, but breaks when used in my code:

```ascii
(node:306360) UnhandledPromiseRejectionWarning: Error: Unknown field: tag
    at F:\DNV\Code\node_modules\gitlog\dist\gitlog.cjs.development.js:166:15
    at Array.forEach (<anonymous>)
    at createCommandArguments (F:\DNV\Code\node_modules\gitlog\dist\gitlog.cjs.development.js:164:20)
    at gitlog (F:\DNV\Code\node_modules\gitlog\dist\gitlog.cjs.development.js:215:26)   
    at process (F:\DNV\Code\log-gen.js:49:25)
    at Object.<anonymous> (F:\DNV\Code\log-gen.js:71:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

**Comment by domharrington** [comment]
Hey! I think this got released in [v4.0.8](https://github.com/domharrington/node-gitlog/pull/76#issuecomment-1548839973) - can you confirm? @hipstersmoothie is the primary maintainer on this repo 🙏
